### ISSUE TITLE
Xmonad for Void Linux

### ISSUE THREAD

**Issue by ghost** [xmonad/xmonad-web#76] opened 2023-02-26 18:34 UTC
Hi could you add Xmonad void linux install pls?

**Comment by slotThe** [comment] 2023-02-26 19:06
Duplicate of #57; the tl;dr is that XMonad is not packaged for Void.  If you want to install it, you'll want to build from source, see [install](https://xmonad.org/INSTALL.html) (note that this even lists dependencies for Void).

**Closed as completed by slotThe** 2023-02-26 19:06 UTC
